server:
  port: 8082

spring:
  application:
    name: seller-service
  kafka:
    bootstrap-servers: localhost:9092
    topic: user-seller-topic
    consumer:
      group-id: seller-service
      auto-offset-reset: earliest
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://127.0.0.1:9000/oauth2/jwks
management:
  tracing:
    enabled: true
    sampling:
      probability: 0.1
  endpoints:
    web:
      exposure:
        include: prometheus, health
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans